---
title: "Yeast Run CAPE"
author: Anna L Tyler
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    collapsed: no
    toc: yes
    toc_float: yes
---

The purpose of this workflow is to run cape on the yeast data.
The experiment name specifies which parameter file to use.

```{r get_exp_name}
library(here)

args <- commandArgs(trailingOnly=T)
exp.name = args[1]
delete_previous <- as.logical(args[2])

if(is.na(exp.name)){
    exp.name <- "chr15"
    delete_previous <- FALSE
}

results.dir <- here("Results", exp.name)
remove_chr9 = TRUE
```

```{r delete_old_data}
if(delete_previous){
    patterns <- c(".txt", ".csv", ".RDS", ".jpg", ".pdf")
    to.delete <- unlist(lapply(patterns, function(x) list.files(results.dir, pattern = x, full.names = TRUE)))
    unlink(to.delete)
}
```

```{r load_code}
all.fun <- list.files(here("Code"), full.names = TRUE, pattern = ".R")
for(i in 1:length(all.fun)){source(all.fun[i])}
```

```{r load_cape, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
#load local version of cape code
needed.libraries <- c("pheatmap")
load_libraries(needed.libraries, personal.library = TRUE)
load_latest_cape(here("Code", "cape"), personal.library = TRUE)
```

Load file and run cape.

```{r read_data}
pop <- read_population(filename = here("Data", "scaffold_72h_data_rqtl1_form_new_11_16_21.csv"),
  id_col = 1, na_strings = NA)
#str(pop)

cross_obj <- cape2mpp(pop)
pheno_obj <- cross_obj[[1]]

#log transform the phenotypes
pheno_obj$pheno <- apply(pheno_obj$pheno, 2, log10)
#mean center
pheno_obj$pheno <- apply(pheno_obj$pheno, 2, function(x) x - mean(x, na.rm = TRUE))

if(remove_chr9){
  geno <- cross_obj[[2]]$geno[,,which(cross_obj[[1]]$chromosome != 9)]
}else{
  geno <- cross_obj[[2]]$geno
}

#str(pheno_obj)
geno_obj <- geno
#str(geno_obj)

```


```{r run_cape}
final.file <- file.path(results.dir, "cross.RDS")

if(!file.exists(final.file)){

  final_obj <- run_cape(pheno_obj, geno_obj, 
    results_file = "cross.RDS", p_or_q = 0.05, n_cores = 4, 
    initialize_only = FALSE, verbose = TRUE, run_parallel = FALSE, 
    param_file = file.path(results.dir, "cape.parameters.yml"), 
    yaml_params = NULL, results_path = results.dir)
}else{
  final_obj <- readRDS(final.file)
  geno_obj <- readRDS(file.path(results.dir, "cross_geno.RDS"))
  pairscan_obj <- readRDS(file.path(results.dir, "cross_pairscan.RDS"))
}
```

## Motifs

First we look at motifs in this network. There is no enrichment of any 
type of motif.

```{r motif_enrichment, fig.width = 7, fig.height = 5}
motif.file <- here(results.dir, "Motif.Results.RDS")

if(!file.exists(motif.file)){
  motif.obj <- find.motifs(final_obj)
  motif.count <- count.motifs(motif.obj)
  motif.enrich <- motif.enrichment(final_obj)
  saveRDS(motif.enrich, motif.file)
}else{
  motif.enrich <- readRDS(motif.file)
}

#jpeg("~/Desktop/motifs.jpg", width = 7, height = 5, units = "in", res = 300)
fig.cols <- c(1:3, 6:8)
par(mar = c(8, 4, 4, 2))
main.shift = 0.3; col.text.shift = 0.27; row.text.shift = 0.3; col.text.rotation = 45
imageWithText(motif.enrich$overlayed[,fig.cols], 
    col.names = colnames(motif.enrich$motif.counts)[fig.cols], 
			row.names = rownames(motif.enrich$motif.counts), 
      main = "Overlay of Enriched (brown) and Depleted (blue) Motifs", 
			class.mat = motif.enrich$overlayed.class.mat[,fig.cols], 
      grad.dir = "low", color.fun = "exponential", exp.steepness = 10, 
			global.color.scale = FALSE, global.min = 0, global.max = 1, cex = 1.2, 
			col.text.adj = 1, main.shift = main.shift, col.text.shift = col.text.shift, 
			row.text.shift = row.text.shift, col.text.rotation = col.text.rotation,
      col.scale = c("brown", "blue"), light.dark = "l")	 	
#dev.off()
```
