#This function looks for statistical enrichment of each class of motifs
#It does this by permuting the edge signs 
#This takes the object generated by build.motif.net()
#permutations = 10000; sep.main = TRUE; include.covar = FALSE; collapsed.net = TRUE; plot.dist = TRUE; directed = FALSE; count.col = "green"; enriched.col = "brown"; depleted.col = "blue"; pdf.filename = "Motif.Distributions.pdf"


motif.enrichment <- function(data.obj, permutations = 10000, sep.main = TRUE, 
include.covar = FALSE, collapsed.net = TRUE, plot.dist = TRUE, 
directed = FALSE, count.col = "green", enriched.col = "brown", 
depleted.col = "blue", pdf.filename = "Motif.Distributions.pdf"){

	show.text = TRUE
	
	num.pheno <- ncol(get_pheno(data.obj, scan_what = data.obj$scan_what))
	
	orig.motifs <- find.motifs(data.obj, collapsed.net = collapsed.net, include.covar = include.covar)
	
	if(!directed){
		orig.motifs <- count.motifs(orig.motifs)
		orig.motif.counts <- orig.motifs[[1]][[1]]
		orig.motif.table <- orig.motifs[[1]][[2]]
		# orig.motif.table <- count.motifs(orig.motifs, write.table = TRUE)
		}else{
		orig.motif.table <- count.motifs.directed(orig.motifs)[[2]]	
		}
	
	num.motif.classes <- dim(orig.motif.table)[2]
	perm.table <- array(NA, dim = c(num.pheno, num.motif.classes, permutations))

	motif.nets <- build.adj.mats(data.obj, collapsed.net = collapsed.net, include.covar = include.covar)
	
	#shuffle the edge weights in the network
	#keeping the topology the same
	shuffle.edges <- function(motif.net, sep.main){
		if(sep.main){
			gene.net.ind <- 1:(dim(motif.net)[1]-1)
			pheno.net.ind <- dim(motif.net)[1]
			gene.net <- motif.net[, gene.net.ind,drop=FALSE]
			pheno.net <- motif.net[, pheno.net.ind, drop=FALSE]
			int.locale <- which(gene.net != 0)
			int.weights <- gene.net[int.locale]
			main.locale <- which(pheno.net != 0)
			main.weights <- pheno.net[main.locale]
			gene.net[int.locale] <- sample(int.weights)
			pheno.net[main.locale] <- sample(main.weights)
			motif.net <- cbind(gene.net, pheno.net)
			}else{
			edge.locale <- which(motif.net != 0)
			edge.weights <- motif.net[edge.locale]
			motif.net[edge.locale] <- sample(edge.weights)
			}
		return(motif.net)
		}

	
	do.perm <- function(){
		shuff.nets <- lapply(motif.nets, function(x) shuffle.edges(x, sep.main))	
		names(shuff.nets) <- names(motif.nets)
		shuff.motifs <- find.motifs2(shuff.nets)	
		if(!directed){
			shuff.motif.counts <- count.motifs(shuff.motifs)[[1]][[2]]
			}else{
			shuff.motif.counts <- count.motifs.directed(shuff.motifs)[[1]][[2]]
			}
		return(shuff.motif.counts)
		}
	
	# registerDoParallel()
	# perm.list <- foreach(n = 1:permutations) %dopar% {
		# do.perm()
		# }
	
	if(permutations > 0){
	for(i in 1:permutations){
		report.progress(i, permutations)
		shuff.nets <- lapply(motif.nets, function(x) shuffle.edges(x, sep.main))	
		names(shuff.nets) <- names(motif.nets)
		shuff.motifs <- find.motifs2(shuff.nets)	
		if(!directed){
			shuff.motif.counts <- count.motifs(shuff.motifs)[[1]][[2]]
			}else{
			shuff.motif.counts <- count.motifs.directed(shuff.motifs)[[1]][[2]]
			}
		perm.table[,,i] <- shuff.motif.counts
		}
		}
	
	#for each phenotype and each type of motif,
	#compare the sampled frequencies to the
	#observed frequencies

	# pdf(pdf.filename, width = dim(layout.mat)[2]*3, height = dim(layout.mat)[1]*3)


	if(plot.dist){
	layout.mat <- get.layout.mat(10, "landscape")
	pdf(pdf.filename, width = dim(layout.mat)[2]*3, height = dim(layout.mat)[1]*3)
	layout(layout.mat)
	}else{
	pdf(pdf.filename, width = 12, height = 8)	
	}
		
	enriched.p <- matrix(NA, nrow = dim(orig.motif.table)[1], ncol = dim(orig.motif.table)[2])
	depleted.p <- matrix(NA, nrow = dim(orig.motif.table)[1], ncol = dim(orig.motif.table)[2])
	colnames(enriched.p) <- colnames(depleted.p) <- colnames(orig.motif.table)
	rownames(enriched.p) <- rownames(depleted.p) <- rownames(orig.motif.table)
	for(i in 1:dim(orig.motif.table)[1]){
		for(j in 1:dim(orig.motif.table)[2]){
			
			if(plot.dist && permutations > 0){
				if(length(which(is.finite(perm.table[i,j,]))) > 0){
				hist(perm.table[i,j,], xlim = c(0,1), xlab = paste("Distribution of", colnames(orig.motif.table)[j], "motifs in", rownames(orig.motif.table)[i]), main = paste("Distribution of", colnames(orig.motif.table)[j], "\nmotifs in", rownames(orig.motif.table)[i]))
				abline(v = orig.motif.table[i,j], col = "red", lwd = 3)
				}
				}

				if(permutations > 0){
				depleted.p[i,j] = length(which(perm.table[i,j,] <= orig.motif.table[i,j]))/permutations
				enriched.p[i,j] = length(which(perm.table[i,j,] >= orig.motif.table[i,j]))/permutations
				}
		}
	}
	
	
	#overlay the enriched and depleted tables
	if(permutations > 0){
	enriched <- matrix(NA, ncol = dim(orig.motif.table)[2], nrow = dim(depleted.p)[1])
	colnames(enriched) <- colnames(orig.motif.table)
	depleted <- matrix(NA, ncol = dim(orig.motif.table)[2], nrow = dim(depleted.p)[1])
	colnames(depleted) <- colnames(orig.motif.table)
	entry.locale <- match(colnames(enriched), colnames(depleted.p))
	enriched <- enriched.p[,entry.locale]
	depleted <- depleted.p[,entry.locale]	

	
	#overlay the matrices by putting the minimum p value of the two in each entry,
	#and record the class, so we can plot with imageWithText
	#the diff mat shows where the enriched p values are smaller
	diff.mat <- enriched-depleted
	overlayed <- matrix(NA, dim(enriched)[1], dim(enriched)[2])
	class.mat <- matrix(NA, dim(enriched)[1], dim(enriched)[2])
	
	overlayed[which(diff.mat <= 0)] <- enriched[which(diff.mat <= 0)]
	class.mat[which(diff.mat <= 0)] <- 1
	
	overlayed[which(diff.mat > 0)] <- depleted[which(diff.mat > 0)]
	class.mat[which(diff.mat > 0)] <- 2
	}
	
	fig.cols <- c(1:3, 6:8)
	
		layout(matrix(1))
		par(mar = c(7,7,7,4))
		imageWithText(orig.motif.counts, show.text = show.text, col.names = colnames(orig.motif.table), row.names = rownames(orig.motif.table), cex = 1, main = "Motif Counts", col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, col.scale = count.col, light.dark = "l")
		imageWithText(orig.motif.table, col.names = colnames(orig.motif.table), row.names = rownames(orig.motif.table), cex = 1, main = "Motif Frequency", col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, show.text = show.text, col.scale = count.col, light.dark = "l")
		imageWithText(orig.motif.counts, show.text = FALSE, col.names = colnames(orig.motif.table), row.names = rownames(orig.motif.table), cex = 1, main = "Motif Counts", col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, col.scale = count.col, light.dark = "l")		
		if(permutations > 0){
		imageWithText(enriched, col.names = colnames(enriched), row.names = rownames(enriched), cex = 1, main = "Significantly Enriched Motifs", grad.dir = "low", exp.steepness = 10, col.scale = enriched.col, col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, show.text = show.text, light.dark = "l")
		imageWithText(depleted, col.names = colnames(depleted), row.names = rownames(depleted), cex = 1, main = "Significantly Depleted Motifs", grad.dir = "low", exp.steepness = 10, col.scale = depleted.col, col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, show.text = show.text, light.dark = "l")
	 	imageWithText(overlayed, col.names = colnames(depleted), row.names = rownames(depleted), main = paste("Overlay of Enriched (", enriched.col, ") and Depleted (", depleted.col, ")", sep = ""), class.mat = class.mat, grad.dir = "low", color.fun = "exponential", exp.steepness = 10, global.color.scale = FALSE, global.min = 0, global.max = 1, cex = 1, col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, show.text = show.text, col.scale = c(enriched.col, depleted.col), light.dark = "l")
	 	imageWithText(overlayed[,fig.cols], col.names = colnames(depleted)[fig.cols], row.names = rownames(depleted), main = paste("Overlay of Enriched (", enriched.col, ") and Depleted (", depleted.col, ")", sep = ""), class.mat = class.mat[,fig.cols], grad.dir = "low", color.fun = "exponential", exp.steepness = 10, global.color.scale = FALSE, global.min = 0, global.max = 1, cex = 1, col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, show.text = show.text, col.scale = c(enriched.col, depleted.col), light.dark = "l")
	 	imageWithText(overlayed[,fig.cols], col.names = colnames(depleted)[fig.cols], row.names = rownames(depleted), main = paste("Overlay of Enriched (", enriched.col, ") and Depleted (", depleted.col, ")", sep = ""), class.mat = class.mat[,fig.cols], grad.dir = "low", color.fun = "exponential", exp.steepness = 10, global.color.scale = FALSE, global.min = 0, global.max = 1, cex = 1, col.text.adj = 1, main.shift = 0.2, col.text.shift = 0.17, show.text = FALSE, col.scale = c(enriched.col, depleted.col), light.dark = "l")	 	
		}
		dev.off()
	
	if(permutations > 0){
	result <- list(orig.motifs, orig.motif.table, orig.motif.counts, enriched.p, depleted.p, overlayed, class.mat)
	names(result) <- c("net.motifs", "motif.frequency", "motif.counts", "p.value.for.enrichment", "p.value.for.depletion", "overlayed", "overlayed.class.mat")
	}else{
	result <- list(orig.motifs, orig.motif.table, orig.motif.counts)
	names(result) <- c("net.motifs", "motif.frequency", "motif.counts")
		}
	invisible(result)
	
}