#This function finds motifs in the object generated by build motif net


find.motifs2 <- function(motif.nets){
			
			
	num.pheno <- length(motif.nets)
	pheno.names <- names(motif.nets)
		
	#to find the complete three-node motifs, look at each
	#edge and verify that each gene has a connection to the
	#phenotype as well. Each phenotype will get its own set
	#of motifs
	all.triplets <- vector(mode = "list", length = num.pheno)
	names(all.triplets) <- pheno.names
	
	all.triplet.signs <- vector(mode = "list", length = num.pheno)
	names(all.triplet.signs) <- pheno.names
	

	
	for(ph in 1:num.pheno){

		pheno.locale <- which(colnames(motif.nets[[ph]]) == pheno.names[ph])
		all.ind <- 1:dim(motif.nets[[ph]])[1]
		gene.ind <- all.ind[-pheno.locale]
		
		gene.edge.locale <- which(motif.nets[[ph]][gene.ind,gene.ind] != 0, arr.ind = TRUE)
		pheno.net <- motif.nets[[ph]][, pheno.locale, drop=FALSE]
		gene.net <- motif.nets[[ph]][gene.ind, gene.ind]
		
		triplet.list <- matrix(NA, ncol = 3, nrow = dim(gene.edge.locale)[1])
		triplet.signs <- matrix(NA, ncol = 3, nrow = dim(gene.edge.locale)[1])
		colnames(triplet.list) <- c("source", "target", "pheno")
		colnames(triplet.signs) <- c("source-target", "source-Ph", "target-Ph")
		for(g in 1:dim(gene.edge.locale)[1]){
			#for each edge, look for an entry in the phenotype
			#matrix corresponding to each gene in the interaction
			#to find open triplets, just change && to ||
			if(pheno.net[gene.edge.locale[g,1],1] != 0 && pheno.net[gene.edge.locale[g,2],1] != 0){
				triplet.list[g,] <- c(colnames(gene.net)[gene.edge.locale[g,]], pheno.names[ph])
				triplet.signs[g,] <- c(sign(gene.net[gene.edge.locale[g,1], gene.edge.locale[g,2]]), sign(pheno.net[gene.edge.locale[g,1],1]), sign(pheno.net[gene.edge.locale[g,2],1]))
				}
			}
		#take out the NA rows, and the non-interactions 
		#for each phenotype
		non.na.locale <- which(!is.na(triplet.list[,1]))
		triplet.list <- triplet.list[non.na.locale,,drop=FALSE]
		triplet.signs <- triplet.signs[non.na.locale,,drop=FALSE]

		all.triplets[[ph]] <- triplet.list	
		all.triplet.signs[[ph]] <- triplet.signs
	}
	
	result <- list(all.triplets, all.triplet.signs)
	return(result)
	
	
}