#!/bin/bash
#SBATCH -J yeast_cape
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-48:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# example use: sbatch --export=exp_name="GAL_query",delete_previous="TRUE" yeast_query_cape

cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec /projects/carter-lab/atyler/Containers/som.sif R -e 'rmarkdown::render(here::here("Documents", "Query_CAPE.Rmd"))' --args "$exp_name" "$delete_previous"
